import unittest
from types import SimpleNamespace
from unittest.mock import Mock

from fastapi import HTTPException
import main
from routes.gallery import read_images


class GalleryRouteTests(unittest.TestCase):
    def test_gallery_and_migrated_routes_are_registered_once(self):
        # FastAPI keeps included routers as internal placeholders in the
        # current runtime, so inspect the public route registry generated by
        # the application instead of only direct APIRoute instances.
        paths = list(main.app.openapi()["paths"])

        for path in (
            "/api/images",
            "/api/artists",
            "/api/months",
            "/api/library/jobs",
        ):
            self.assertEqual(paths.count(path), 1, path)
        self.assertIn("/api/web-config", paths)
        self.assertIn("/api/pixiv-config", paths)

    def test_gallery_route_maps_service_contract_and_normalizes_only_db(self):
        service = Mock()
        service.images.return_value = (
            [{"image_id": 7}],
            1,
            [{"month": "2026-08", "count": 1}],
        )
        request = SimpleNamespace(
            app=SimpleNamespace(
                state=SimpleNamespace(
                    runtime_context=SimpleNamespace(gallery_service=service),
                ),
            ),
        )

        result = read_images(
            request,
            month="2026-08",
            artist_id=8,
            search="title",
            only_db=None,
            sort_mode="oldest",
            limit=24,
            offset=48,
        )

        self.assertEqual(result["images"], [{"image_id": 7}])
        self.assertEqual(result["total"], 1)
        self.assertEqual(result["months"], [{"month": "2026-08", "count": 1}])
        service.images.assert_called_once_with(
            month="2026-08",
            artist_id=8,
            search="title",
            limit=24,
            offset=48,
            only_db=False,
            sort_mode="oldest",
        )

    def test_gallery_route_requires_ready_runtime_context(self):
        request = SimpleNamespace(app=SimpleNamespace(state=SimpleNamespace()))

        with self.assertRaises(HTTPException) as context:
            read_images(request)
        self.assertEqual(context.exception.status_code, 503)


if __name__ == "__main__":
    unittest.main()
